name: CI - Lint & Analyse

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-yaml:
    name: Lint YAML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint YAML (yamllint)
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .
          config_file: .yamllint.yml # Optionnel, sinon yamllint par défaut

  lint-bash:
    name: Lint Bash scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installer ShellCheck
        run: sudo apt-get install -y shellcheck
      - name: Lint des scripts Bash
        run: |
          find . -type f -name '*.sh' -exec shellcheck {} +

  docker-compose-validate:
    name: Validation docker-compose
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Vérifier les fichiers docker-compose
        run: |
          find . -type f -name 'docker-compose.yml' -exec docker-compose -f {} config \;

  trivy-scan:
    name: Scan sécurité Trivy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Scanner la configuration avec Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          scan-ref: . 